### PR TITLE
Borderless window

### LINKED ISSUE #28: Allow user to toggle title bar
First of all: Thank you for starting this project. This has been a thing I needed for quite some time.

While using Pennywise, the title bar takes up quite some space and when watching full screen videos it is simply not needed. Thus I would like to suggest the option to toggle the title bar. The API needed for this feature is quite simple to implement (https://electronjs.org/docs/api/frameless-window).

image

It would also be possible to simply hide the operating system's title bar in all cases and set the draggable region to the nav bar. In this case the user could move the window when dragging the nav bar. On screens where no nav bar is present (like the welcome screen) the draggable region could be the whole interface because the option does not interfere with any component there.

If this feature is approved by the project's maintainer I would love to contribute a pull request.

### PR DESCRIPTION
**Pull request by alxwrd**
**What does this PR do?**

This adds an option to toggle the window frame from a command line switch. Maybe closes #28?

example gif

---

Now includes a menu item:

menu item example

**What platforms did you test it on?**
Windows 10

### CODE REVIEW

**Comment by akash-joshi** [comment]
Should we maybe add a frameless checkbox on the EmptyPage screen so it works with other platforms too ?

**Comment by alxwrd** [comment]
@akash-joshi good idea. I'll add it as a menu item.

**Comment by alxwrd** [comment]
I've pushed some changes to allow this to be toggle-able from a menu item.

menu item example

**Comment by alxwrd** [comment]
Last commit adds padding to the body to make sure there's always an border so the app can be resized in borderless mode.

I've also hidden overflow on this page so scroll bars will no longer appear.

untitled

**Comment by alxwrd** [comment]
Just rebased this onto master so it includes the changes from #90.

**Comment by nrabreu** [comment]
Looks good! 👍

**Comment by akash-joshi** [comment]
@alxwrd 
Hey, since this repo seems kind of date, I thought of continuing this project by forking it. Would you consider throwing your PR to my fork : https://github.com/akash-joshi/pennywise-plus

**Comment by kamranahmedse** [comment]
Thanks @alxwrd for the PR. I was thinking that we should still have the control buttons on the frameless window which [can be achieved on Mac OS using `titleBarStyle`](https://electronjs.org/docs/api/frameless-window) but it will need some custom implementation in case of Windows and Linux.

But anyways, we can merge it as it is for now and plan that in any future release. Thanks :)

**Comment by alxwrd** [comment]
@kamranahmedse excellent, thanks. Would you mind doing a new release when you have a chance?

**Comment by akash-joshi** [comment]
@alxwrd you can see how Hyper does it as a reference

**Pull request merged**
