### PR TITLE
Make 'empty-page' responsive

### PR DESCRIPTION
**Pull request by alxwrd**
hello :wave: !

This adds `@media` queries to the elements on the `empty-page` to stop the scroll bars appearing when pennywise is set to a smaller size.

The logo has had it's size changed to `vh` so it can be kept as long as possible.

| Before                                                                          | After                                                                          |
|---------------------------------------------------------------------------------|--------------------------------------------------------------------------------|
|  [before](https://i.imgur.com/3Yn6CST.png) |  [after](https://i.imgur.com/HFmauZ2.png) |

### Before gif
before

### After gif
after

<details>
 <summary>Previous</summary>
<p>

This changes size values in `empty-page/style.scss` to use `vh` instead of `px` values. This means if Pennywise is small, the url bar is still visible, and scroll bars don't appear.

I tried to keep the initial open state sizes very similar, but there is some slight differences.

| Before                                                                          | After                                                                          |
|---------------------------------------------------------------------------------|--------------------------------------------------------------------------------|
|  [before](https://i.imgur.com/rpGtkmk.png) |  [after](https://i.imgur.com/cfE1NuE.png) |

### Before gif
before

### After gif
after

</p>
</details>

### CODE REVIEW

**Comment by The-Code-Monkey** [comment]
This makes it reponsive but unreadable the point of responsiveness is not to make it fit but to make it readable on all devices

**Comment by alxwrd** [comment]
@The-Code-Monkey Thank you for your feedback.

The point when the _text_ really starts to become unreadable is as you hit the < 250px point. However, at this point the _application_ is still perfectly useable.

Side-by-side:

example

Besides, this change isn't about tiny sizes, it's about small sizes. The text below is still readable:

image

**Comment by The-Code-Monkey** [comment]
Still at the end of the day you shouldn't use vh and vw for all of the styles instead. Just shrink the image and that should be enough

**Comment by alxwrd** [comment]
I've pushed some changes to use `@media` queries instead. See initial post.

**Comment by akash-joshi** [comment]
The new changes look good 👍

**Comment by alxwrd** [comment]
Hi @kamranahmedse. Have you had chance to review this? If this isn't a change you would want I'm happy to close.

**Comment by kamranahmedse** [comment]
@alxwrd thanks for the PR. Could you please change it to hide the image first and then hide the textual content if required on small screens? Apart from that, all looks good.

**Comment by alxwrd** [comment]
@kamranahmedse I've just pushed the requested changes, you can see it in action below.

gif

**Comment by kamranahmedse** [comment]
Thanks

**Pull request merged**
